Changed FmiModifyEditdData::MakeMacroParamRelatedFinalErrorMessage generated message a bit. Removed newline after ',' so that the comma won't be alone in it's own line, but it's united with the macroParam file path: Error: Macro Parameter intepretion failed: Calculation line seems to be missing the '=' operator: result xxx , in 'Omat\Marko\result_no_equal_sign_message'
Message was like this before:

Error: Macro Parameter intepretion failed:
Calculation line seems to be missing the '=' operator:
result xxx
,
in 'Omat\Marko\result_no_equal_sign_message'